"""Add baseline and latest tile urls

Revision ID: 398756177c3e
Revises: 
Create Date: 2026-03-06 21:11:25.345116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '398756177c3e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('validation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tile_url_baseline', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('tile_url_latest', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('validation', schema=None) as batch_op:
        batch_op.drop_column('tile_url_latest')
        batch_op.drop_column('tile_url_baseline')

    # ### end Alembic commands ###
